basePath: /
definitions:
  auth.Login:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  users.User:
    properties:
      confirm_password:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
  description: A Comprehensive Semantic Analysis Web Service.
  title: Content Creator Inshight
  version: "1.0"
paths:
  /:
    get:
      description: Returns pong , just to check server is running
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Get ping response
      tags:
      - Ping
  /login:
    post:
      description: validate login with credentials
      parameters:
      - description: login details
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/auth.Login'
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Validate login
      tags:
      - users
  /signup:
    post:
      description: Creates a new user from signup
      parameters:
      - description: user details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/users.User'
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Creates a new user
      tags:
      - users
  /yt/analyse/video/{video_id}:
    get:
      description: Returns Sentiment analyse of all video comments
      parameters:
      - description: videoID
        in: path
        name: video_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: list analyse detail of video comments
      tags:
      - Yt
  /yt/list/videos/{channelID}:
    get:
      description: Returns list of  Youtube videos with channel id
      parameters:
      - description: channelId
        in: path
        name: channel_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: list youtube videos
      tags:
      - Yt
swagger: "2.0"
